### ISSUE TITLE
User should be able to specify TimelineEvent details

### ISSUE THREAD

**Issue by SteveDZ** [Turbots/oraj-360-tool#12]
<ul>
<li><b>Generic timeline event</b></li>
<ul>
<li>Creationdate</li>
<li>description (description of the type of event, nothing concerning the actual content of the event)</li>
<li>Id of the creator</li>
<li>Id of the employee for whom this event was logged</li>
<li>generatesNotifications?</li>
<li>reminders?</li>
</ul></ul>

<ul>
<li><b>Appointment</b></li>
<ul>
<li>Attendees, date, summary, approval (manager and employee should formally agree on the summary of a meeting)</li>
</ul></ul>

<ul>
<li><b>Training/course</b></li>
<ul>
<li>Period</li>
<li>subject</li>
<li>certificate (if applicable)</li>
</ul></ul>

<ul>
<li><b>Target</b></li>
<ul>
<li>title</li>
<li>deadline</li>
<li>description (Try to define measurable criteria in the target description)</li>
</ul></ul>

<ul><li><b>Satisfaction: HAPPY, NEUTRAL, UNHAPPY</b></li></ul>

<ul>
<li><b>Project start/stop</b></li>
<ul>
<li>description</li>
<li>customer</li>
<li>start-date</li>
<li>end-date</li>
</ul></ul>

**Comment by Turbots** [comment]
This issue was moved to oraj-360/oraj360tool#7
