### ISSUE TITLE
User should be notified of future/upcoming events

### ISSUE THREAD

**Issue by SteveDZ** [Turbots/oraj-360-tool#13]
TimelineEvents should be able to generate notifications.
Properties can be added to the TimelineEvent class which allow us to configure an Event to generate notifications.
We can choose to use fixed dates on which we want Events to generate notifications.
Or we can use set reminders on Events that have a certain deadline or end-date.

A process could be created that runs periodically which determines if notifications should be sent.
Also, notification types could be used to distinguish between pop-ups and email notifications.

**Comment by Turbots** [comment]
This issue was moved to oraj-360/oraj360tool#6
