### ISSUE TITLE
A Manager should be able to create new Person

### ISSUE THREAD

**Issue by SteveDZ** [Turbots/oraj-360-tool#14]
A manager should be able to create new Person.
Because we choose to implement a simplified authorisation model for now, also CL's and coaches will be able to create new people.

A manager should be able to provide all necessary data to create a Person.
Another approach would be to invite users by mail. These users can then enrol in a registration process which allows them to supply their personalia and credentials.

**Comment by Turbots** [comment]
This issue was moved to oraj-360/oraj360tool#5
