### ISSUE TITLE
User should be able to search through all people for whom he's responsible

### ISSUE THREAD

**Issue by SteveDZ** [Turbots/oraj-360-tool#2]
Since the list with people a user can see, can become quite extensive, search functionality should be implemented which allows a user to quickly find a specific person.

In a first phase, search should be possible based on:

<ul>
<li>first name</li>
<li>last name</li>
</ul>

This implies that a search action should be implemented in the Persons REST service.

**Comment by Turbots** [comment]
This issue was moved to oraj-360/oraj360tool#14
