### ISSUE TITLE
User should be able to see the date of the last contact between the a person and a manager, CL or coach

### ISSUE THREAD

**Issue by SteveDZ** [Turbots/oraj-360-tool#4]
A logged in user should be able to see when a person's last contact with a BUM, CL or coach took place.

This date should be retrieved from the Timeline Service.
Maybe Service-to-Service calls can be used to automatically call through to the TimelineService.
The TimelineService could contain an action which allows us to receive the last contact date. 
This date can then be set on the Person resource.

**Comment by Turbots** [comment]
This issue was moved to oraj-360/oraj360tool#13
