### ISSUE TITLE
User should be able to see the last 5 satisfaction entries for this person

### ISSUE THREAD

**Issue by SteveDZ** [Turbots/oraj-360-tool#5]
Currently, people enter their satisfaction monthly in their timesheets. This data should also be available in  the threesixty tool.

A Satisfaction (or SatisfactionHistory) Rest service may be necessary to provide this information.

Currently, integration with the timesheet application is difficult, so solutions must be thought of to keep the duplication and extra effort to maintain this information as low as possible.

When the Satisfaction Rest Service eventually becomes available, the Person service can call through to the Satisfaction service, or hypermedia can be added to the Person resource to make the satisfaction data available to the service client.

**Comment by Turbots** [comment]
This issue was moved to oraj-360/oraj360tool#12
