### ISSUE TITLE
User should be able to see a persons availability (project-wise + holidays)

### ISSUE THREAD

**Issue by SteveDZ** [Turbots/oraj-360-tool#6]
An AvailabilityService (or something similar) should be foreseen to enable a user to retrieve a person's availability or holidays. This data is available on sharepoint, but it is uncertain how this could be replicated to the threeSixty tool. 

Perhaps the availability on sharepoint can be exported in csv format and a manual process could be put in place to import the csv in the threesixty tool.

The Person Service could then call through to the AvailabilityService or the Person Resource could be updated to return an additional link allowing us to retrieve this data.

**Comment by kencoenen** [comment]
Personally, I shouldn't replicate the data stored in Sharepoint. You should be able to retreive the data through the Sharepoint Web Services. The ORA/J 360 tool should have a user for authentication and we should use Sharepoint's WSDLs to create stubs.

Only disadvantage is that I've seen quite a lot of projects having difficulties requesting data from Sharepoint (mainly authentication issues, usually Kerberos is used), but it's worth a try before replicating anything.

**Comment by SteveDZ** [comment]
That would definitely be a better solution, were it not that Internal IT isn't currently allowing any integrations with their systems... 
Hopefully, in the near future, this gets allowed after all.

**Comment by Turbots** [comment]
Mijn voorstel: momenteel implementeren we alles in onze timeline service, waar events aan kunnen worden toegevoegd (waaronder ook periodes zoals Projecten, Benchtime, Holidays, ...)

Eens we de awesomeness van de 360 tool hebben aangetoond, kunnen we hopelijk met de sharepoint (of rechtstreeks met exchange) de agendas en vakanties van werknemers kunnen binnenhalen en incorporeren in de timeline. Lets :kiss:  (keep it simple stupid)

**Comment by Turbots** [comment]
This issue was moved to oraj-360/oraj360tool#11
