### ISSUE TITLE
User should be able to see relevant past and future events for a person

### ISSUE THREAD

**Issue by SteveDZ** [Turbots/oraj-360-tool#8]
TimelineService should be created/adapted to allow us to retrieve TimelineEvent information.
TimelineEvent could be one of:

<ul>
<li>Appointment</li>
<li>Course started/finished</li>
<li>Project start/stop</li>
<li>Personal target</li>
<li>Satisfaction entry</li>
</ul>

And possibly others.

Basic timeline-api should look like this:

<ul>
<li>GET: /timeline</li>
<li>GET: /timeline/{personId} </li>
<li>POST: /timeline</li>
<li>PUT/PATCH: /timeline/{timelineEventId} (Update TimelineEvent)</li>
</ul>

**Comment by Turbots** [comment]
This issue was moved to oraj-360/oraj360tool#10
